apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-uploads
  labels:
    app.kubernetes.io/name: hive
    app.kubernetes.io/component: uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
