apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Nivek-Z/hive.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hive-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
